### PR TITLE
Rename the main picture from .JPG to .jpg

### PR DESCRIPTION
**Pull request by BarbourSmith**
I think that the capitalization change is causing the picture to not show up in the community garden

### CODE REVIEW

**Comment by MeticulousMaynard** [comment]
I didn't even realize the picture was broken. I updated it manually when I added the dxf files and never checked that it worked. Oops! Sorry guys!

**Comment by BarbourSmith** [comment]
No worries! The whole point of the garden is that anyone can fix anything so if something is broken it will get fixed 😀

**Comment by MeticulousMaynard** [comment]
not sure this fix worked? I just checked the community garden page on my mobile and I'm still getting the broken picture icon. Are you seeing the image now?

**Comment by BarbourSmith** [comment]
It takes a few minutes for the page to regenerate, but it's looking good to me now:

image


image

**Comment by MeticulousMaynard** [comment]
Okay, I'm seeing it now. I'm too impatient, I guess xD

**Pull request merged**
